version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongo
  api:
    container_name: api-container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_URL: mongodb://mongo:27017/clean
    ports:
      - "8080:8080"
    networks:
      - mongo
networks:
  mongo:
    driver: bridge