version: "3"
services:
  mongo:
    container_name: mongo-container
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongo
  api:
    container_name: api-container
    image: node:14
    working_dir: /usr/src/clean-cdk-api
    restart: always
    command: bash -c "npm install --only=prod && npm i nodemon && npx nodemon ./dist/main/server.js"
    volumes:
      - ./dist/:/usr/src/clean-cdk-api/dist/
      - ./package.json:/usr/src/clean-cdk-api/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    environment:
      MONGO_URL: mongodb://mongo:27017/clean-cdk
    links:
      - mongo
networks:
  mongo:
    driver: bridge